services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: webjetcms-keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 18080
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "18080:18080"
    command: start-dev
    volumes:
      - webjetcms-keycloakdata:/opt/keycloak/data

volumes:
  webjetcms-keycloakdata:
